"""new migration

Revision ID: 5b2275442231
Revises: f489bcbffd57
Create Date: 2023-12-05 07:25:09.024495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2275442231'
down_revision = 'f489bcbffd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
