import logging

SQLALCHEMY_DATABASE_URI = "sqlite:///dev_db.sqlite"
LOGGING_CONFIG = "instance/logging.conf"
LOGGING_LEVEL = logging.INFO
SECRET_KEY = "YWJkOGJiZTktMDIzNS00NWIyLThlZWEtMTUwNzg0NjkzZjExCg=="
ACCESS_TOKEN_TTL_HOURS = 1
REFRESH_TOKEN_TTL_DAYS = 5
